apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: process-exporter
    app.kubernetes.io/version: v1.0.1
  name: process-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 9100
    targetPort: 9256
  selector:
    app.kubernetes.io/name: process-exporter
