apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobmanager-pv-claim
  namespace: flink
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Mi